name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip
          pip3 install --upgrade pip
          pip3 install buildozer cython virtualenv

      - name: Install Android SDK & Accept Licenses
        run: |
          sudo mkdir -p /home/runner/.android
          sudo touch /home/runner/.android/repositories.cfg
          yes | sdkmanager --licenses
          yes | sdkmanager "build-tools;36.0.0"

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk

      - name: Show Logs
        run: |
          cat .buildozer/android/platform/android-sdk/commandlinetools-linux/bin/sdkmanager --list || true
