name: Android Build with Buildozer
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            python3 python3-pip python3-venv \
            libffi-dev libssl-dev libjpeg-dev zlib1g-dev \
            build-essential

      - name: Install Buildozer & Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade buildozer cython virtualenv

      - name: Set Up Android SDK
        run: |
          export ANDROID_HOME=$HOME/.android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          
          # Create Android SDK Directories
          sudo mkdir -p $ANDROID_HOME/cmdline-tools
          sudo mkdir -p $ANDROID_HOME/licenses
          
          # Download Android SDK Command Line Tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          sudo unzip sdk-tools.zip -d $ANDROID_HOME/cmdline-tools
          sudo mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          # Accept All Android SDK Licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # Install Required Android SDK Components
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" "platforms;android-34" \
            "build-tools;34.0.0" "ndk;25.2.9519653"

      - name: Cache Buildozer & Android SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/.android-sdk
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Build APK with Buildozer
        run: |
          export ANDROID_HOME=$HOME/.android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-APK
          path: bin/*.apk

      - name: Show Logs
        run: |
          cat .buildozer/android/platform/android-sdk/commandlinetools-linux/bin/sdkmanager --list || true
