name: Build Kivy Android APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            python3 python3-pip python3-venv \
            libffi-dev libssl-dev libjpeg-dev zlib1g-dev \
            build-essential libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev
      - name: Install Buildozer & Dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade buildozer cython virtualenv kivy
      - name: Set Up Android SDK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          
          # Create SDK Directories
          mkdir -p $ANDROID_HOME/cmdline-tools
          mkdir -p $ANDROID_HOME/licenses
          
          # Download and Extract Android SDK Command Line Tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip -q sdk-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          
          # Accept Android SDK Licenses Automatically
          echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          
          # Install Required SDK Components
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" "platforms;android-33" \
            "build-tools;33.0.2" "ndk;25.2.9519653" \
            "cmdline-tools;latest"
            
          # Verify Installations
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --list_installed
      - name: Cache Buildozer & Android SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ~/android-sdk
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-
      - name: Build APK with Buildozer
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          buildozer -v android debug
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-APK
          path: bin/*.apk
